Added acceptance test in a docker container. Fixed with it a few bugs

diff --git a/debian-packaging/rootfs/usr/share/initramfs-tools/scripts/init-premount/raspi-updater b/debian-packaging/rootfs/usr/share/initramfs-tools/scripts/init-premount/raspi-updater
--- a/debian-packaging/rootfs/usr/share/initramfs-tools/scripts/init-premount/raspi-updater
+++ b/debian-packaging/rootfs/usr/share/initramfs-tools/scripts/init-premount/raspi-updater
@@ -15,39 +15,45 @@ error() {
 
 . /etc/raspi-updater/raspi-updater.conf || error "Could not load raspi-updater.conf"
 
-echo "Waiting for $NET_INTERFACE"
-modprobe "$NET_DRIVER"
+if [ -f /.dockerenv ]; then
+    echo "Docker acceptance test. Skipping network configuration"
+else
+    echo "Waiting for $NET_INTERFACE"
+    modprobe -qb "$NET_DRIVER" || error "Could not load $NET_DRIVER"
 
-for _ in $(seq 1 30); do
-    [ -d "/sys/class/net/$NET_INTERFACE" ] && break
-    printf "."
-    sleep 0.5
-done
-[ -d "/sys/class/net/$NET_INTERFACE" ] || error "$NET_INTERFACE unavailable"
+    for _ in $(seq 1 10); do
+        [ -d "/sys/class/net/$NET_INTERFACE" ] && break
+        printf "."
+        sleep 0.5
+    done
 
-ip link set "$NET_INTERFACE" up
+    ip link set "$NET_INTERFACE" up
 
-if echo "$NET_INTERFACE" | grep '^wlan'; then
-    echo "Connecting $NET_INTERFACE to WiFi network..."
-    /sbin/wpa_supplicant -W -B -i"$NET_INTERFACE" -c /etc/wpa_supplicant/wpa_supplicant.conf || error "$NET_INTERFACE" connection error
+    if echo "$NET_INTERFACE" | grep '^wlan'; then
+        echo "Connecting $NET_INTERFACE to WiFi network..."
+        /sbin/wpa_supplicant -W -B -i"$NET_INTERFACE" -c /etc/wpa_supplicant/wpa_supplicant.conf || error "$NET_INTERFACE" connection error
+    fi
+
+    ip link list "$NET_INTERFACE"
+
+    echo "Configuring $NET_INTERFACE per DHCP"
+    busybox udhcpc -i "$NET_INTERFACE" -A 2 -n  || error "No DHCP response over $NET_INTERFACE."
+
+    ip address list "$NET_INTERFACE"
+
+    for i in $(seq 1 5); do
+        ping -c1 "$SERVER" && break || true
+        echo "Pinging $SERVER $i / 5"
+        sleep 1
+    done
 fi
 
-ip link list "$NET_INTERFACE"
+client-raspi-updater \
+    -id "$ID" \
+    -disk "$DEVICE" \
+    -compression "$COMPRESSION_TOOL" \
+    -address "$SERVER" \
+    -certFile "$CERT_FILE" || error "Updater failed"
 
-echo "Configuring $NET_INTERFACE per DHCP"
-busybox udhcpc -i "$NET_INTERFACE" -A 2 -n  || error "No DHCP response over $NET_INTERFACE"
-
-ip address list "$NET_INTERFACE"
-
-for i in $(seq 1 5); do
-    ping -c1 "$SERVER" && break || true
-    echo "Pinging $SERVER $i / 5"
-    sleep 1
-done
-
-# TODO: remove this after tests are finished
-DEVICE=/tmp/updater.img
-dd if=/dev/zero of="$DEVICE" bs=$((64*1024*1024)) count=1
-raspi-updater -client -id "$ID" -device "$DEVICE" -compression "$COMPRESSION_TOOL" -address "$SERVER" -certFile "$CERT_FILE" || error "Updater failed"
-
-sleep 10
+echo "Success!"
+sleep 1
